export type UiLocale = 'en' | 'de';

export const UI_COPY = {
  en: {
    localDevice: 'Local on this device', activityNow: 'AI activity now', monitoringOff: 'Ready to observe', stopped: 'READY', workingNow: 'WORKING NOW', openIdle: 'READY', notRunning: 'MONITORING',
    startHelp: 'Start monitoring to see supported AI work as it happens.', summaryPreserved: 'Your AI Footprint is saved locally. Continue whenever you want.', monitoringStopped: 'Observation ready',
    workingEvidence: 'Supported AI work is happening now.', idleEvidence: 'Your supported AI app is ready. Forkit will highlight it when work begins.', noApp: 'Ready for your next AI session', noAppHelp: 'Monitoring is active and will surface supported AI work as it happens.',
    observed: 'Observed', validAwake: 'valid awake time', aiActive: 'AI active', supportedWork: 'supported app work', activityRatio: 'Activity ratio', ratioNote: 'active ÷ observed', overhead: 'Forkit overhead', measuredLocally: 'measured locally', warmingUp: 'measuring…', working: 'Working', openIdleLegend: 'Ready',
    startMonitoring: 'Start Monitoring', stopMonitoring: 'Stop Monitoring', clearHistory: 'Clear history', observation: 'Your observation', earlyObservation: 'Your Footprint is taking shape', earlyObservationCopy: 'Every observed minute adds more detail to your AI Footprint.', observationShows: 'What your AI activity shows.',
    footprint: 'Your AI Footprint', modelRecord: 'model record', modelRecords: 'model records',
    modelRecordsLabel: 'Model records', loaded: '{count} loaded', modelStorage: 'Model storage', recognizedBytes: 'recognized logical bytes', localEngines: 'Local engines', verifiedAvailable: 'verified available now', createShare: 'Create share card', scanAgain: 'Scan again',
    optionalComparison: 'Optional global comparison', comparisonQuestion: 'How does your AI activity compare?', comparisonCopy: 'Explore your position among participating Forkit observations.', globalProgress: 'Your global comparison is taking shape · {remaining} until it’s ready.', seeGlobal: 'See my global position', reviewSharing: 'Review before sharing.', payloadIntro: 'This is the complete aggregate that would leave this device:', shareCompare: 'Share aggregates & compare', keepLocal: 'Keep everything local', noIdentity: 'No account or device identifier. Global contribution is not available in this version.',
    technical: 'Technical details', engines: 'Available engines', modelsDevice: 'Models in use', appsTools: 'AI apps running', probeNotes: 'Probe notes', measurementBoundary: 'How Forkit measures', activityMeasurement: 'AI activity', loadedModel: 'Loaded model', storage: 'Model storage', notMeasured: 'Not measured', forkitResources: 'Forkit resources',
    workingBoundary: 'Recent activity from supported AI app processes.', loadedBoundary: 'Provider-confirmed loaded model.', storageBoundary: 'Recognized local model file sizes.', notMeasuredCopy: 'Prompts, tokens, energy, cost, GPU attribution, per-app network traffic, or exclusive task ownership.',
    noEngine: '', installedNoLoaded: '', modelsLoaded: '{count} {models} loaded', model: 'model', models: 'models', stored: 'stored', noModel: '', processActivity: 'Running locally', detectedNotRunning: '', noTool: '', noProbe: '',
    noPrivateFooter: 'No weights, prompts, commands, paths, config values, account data, or upload', shareTitle: 'Your AI Footprint', shareHeading: 'Your measured AI activity.', share: 'Share', savePng: 'Save PNG', copyImage: 'Copy Image', copyCaption: 'Copy Caption', close: 'Close', sharePrivacy: 'Measured totals and supported tool names only. Chat titles, workspaces, paths, and device identity stay out.', copied: 'Copied', copyUnavailable: 'Image copy is unavailable in this system view. Save the PNG instead.',
    myFootprint: 'MY AI FOOTPRINT', activeTool: 'ACTIVE TOOL', activeTools: 'ACTIVE TOOLS', localModels: 'LOCAL MODELS', observedLocally: 'Observed locally · Forkit AI Footprint', deviceQuestion: 'How much AI is working on your device?', shareActive: 'AI-ACTIVE',
    clearConfirm: 'Clear this local monitoring history?', scanning: 'Scanning local metadata…', refreshed: 'Footprint refreshed locally.', scanFailed: 'Scan could not be refreshed.',
    activeShareFallback: 'Supported AI tools were working during {ratio} of this observation.', footprintFallback: '{count} supported local {records} found.', shareActivity: 'Observed {observed}; AI-active {active} ({ratio}).', shareTool: 'Supported AI activity: {tools}.', shareModels: '{count} local {models}; {storage} recognized model files.', captionFirst: 'My AI was actively working during {ratio} of this observation.', captionQuestion: 'How much AI is actually working on your device?',
    appTitle: 'Forkit AI Footprint', menuStopped: '○ Stopped', menuMonitoring: '● Monitoring', menuWorking: '● Monitoring · {count} working', openFootprint: 'Open AI Footprint', quitForkit: 'Quit Forkit', serviceUnavailable: '○ Service unavailable', serviceStopped: 'Service stopped',
    closeTitle: 'Forkit will keep monitoring in the background.', closeBody: 'You can reopen it or stop monitoring anytime from the Forkit icon. If the macOS menu bar is hidden, move the pointer to the top edge to reveal it.', gotIt: 'Got it', dontShow: "Don’t show this again", quitTitle: 'Stop monitoring and quit?', keepMonitoring: 'Keep Monitoring', stopQuit: 'Stop & Quit', fatalService: 'The local AI Footprints service could not start.', fatalStopped: 'The local service stopped unexpectedly. No monitoring remains active.', quit: 'Quit',
    insightMostlyIdle: 'This observation captured a light AI activity pattern.', insightActivityProduct: '{product} was working during {percent}% of your observation.', insightActivityGeneric: 'Supported AI tools were working during {percent}% of your observation.', insightLongest: 'Your longest continuous AI-active period was {duration}.', insightMulti: 'Active AI work was observed across {count} supported tools.', insightModelsUnused: '{count} local models are ready for a future session.', insightFocused: 'All observed AI activity came from {product}.',
  },
  de: {
    localDevice: 'Lokal auf diesem Gerät', activityNow: 'KI-Aktivität jetzt', monitoringOff: 'Bereit zur Beobachtung', stopped: 'BEREIT', workingNow: 'ARBEITET JETZT', openIdle: 'BEREIT', notRunning: 'MONITORING',
    startHelp: 'Starten Sie das Monitoring und sehen Sie unterstützte KI-Arbeit in Echtzeit.', summaryPreserved: 'Ihr AI Footprint ist lokal gespeichert. Sie können jederzeit fortfahren.', monitoringStopped: 'Beobachtung bereit',
    workingEvidence: 'Unterstützte KI-Arbeit findet gerade statt.', idleEvidence: 'Ihre unterstützte KI-App ist bereit. Forkit hebt sie hervor, sobald die Arbeit beginnt.', noApp: 'Bereit für Ihre nächste KI-Sitzung', noAppHelp: 'Das Monitoring ist aktiv und zeigt unterstützte KI-Arbeit, sobald sie stattfindet.',
    observed: 'Beobachtet', validAwake: 'gültige aktive Gerätezeit', aiActive: 'KI aktiv', supportedWork: 'Arbeit unterstützter Apps', activityRatio: 'Aktivitätsanteil', ratioNote: 'aktiv ÷ beobachtet', overhead: 'Forkit-Ressourcen', measuredLocally: 'lokal gemessen', warmingUp: 'wird gemessen…', working: 'Arbeitet', openIdleLegend: 'Bereit',
    startMonitoring: 'Monitoring starten', stopMonitoring: 'Monitoring stoppen', clearHistory: 'Verlauf löschen', observation: 'Ihre Beobachtung', earlyObservation: 'Ihr Footprint nimmt Gestalt an', earlyObservationCopy: 'Jede beobachtete Minute ergänzt Ihren AI Footprint.', observationShows: 'Das zeigt Ihre KI-Aktivität.',
    footprint: 'Ihr AI Footprint', modelRecord: 'Modelldatensatz', modelRecords: 'Modelldatensätze',
    modelRecordsLabel: 'Modelldatensätze', loaded: '{count} geladen', modelStorage: 'Modellspeicher', recognizedBytes: 'erkannte logische Dateibytes', localEngines: 'Lokale Engines', verifiedAvailable: 'aktuell verifiziert verfügbar', createShare: 'Share-Karte erstellen', scanAgain: 'Erneut scannen',
    optionalComparison: 'Optionaler globaler Vergleich', comparisonQuestion: 'Wie lässt sich Ihre KI-Aktivität vergleichen?', comparisonCopy: 'Entdecken Sie Ihre Position unter teilnehmenden Forkit-Beobachtungen.', globalProgress: 'Ihr globaler Vergleich nimmt Gestalt an · in {remaining} ist er bereit.', seeGlobal: 'Meine globale Position ansehen', reviewSharing: 'Vor dem Teilen prüfen.', payloadIntro: 'Dies ist das vollständige Aggregat, das dieses Gerät verlassen würde:', shareCompare: 'Aggregate teilen & vergleichen', keepLocal: 'Alles lokal behalten', noIdentity: 'Kein Konto und keine Gerätekennung. Globale Beiträge sind in dieser Version nicht verfügbar.',
    technical: 'Technische Details', engines: 'Verfügbare Engines', modelsDevice: 'Modelle in Verwendung', appsTools: 'Laufende KI-Apps', probeNotes: 'Prüfhinweise', measurementBoundary: 'So misst Forkit', activityMeasurement: 'KI-Aktivität', loadedModel: 'Geladenes Modell', storage: 'Modellspeicher', notMeasured: 'Nicht gemessen', forkitResources: 'Forkit-Ressourcen',
    workingBoundary: 'Aktuelle Aktivität unterstützter KI-App-Prozesse.', loadedBoundary: 'Vom Anbieter bestätigtes geladenes Modell.', storageBoundary: 'Erkannte lokale Modelldateigrößen.', notMeasuredCopy: 'Prompts, Tokens, Energie, Kosten, GPU-Zuordnung, Netzwerkverkehr pro App oder exklusive Aufgabenzuordnung.',
    noEngine: '', installedNoLoaded: '', modelsLoaded: '{count} {models} geladen', model: 'Modell', models: 'Modelle', stored: 'gespeichert', noModel: '', processActivity: 'Läuft lokal', detectedNotRunning: '', noTool: '', noProbe: '',
    noPrivateFooter: 'Keine Gewichte, Prompts, Befehle, Pfade, Konfigurationswerte, Kontodaten oder Uploads', shareTitle: 'Ihr AI Footprint', shareHeading: 'Ihre gemessene KI-Aktivität.', share: 'Teilen', savePng: 'PNG speichern', copyImage: 'Bild kopieren', copyCaption: 'Text kopieren', close: 'Schließen', sharePrivacy: 'Nur gemessene Summen und Namen unterstützter Tools. Chat-Titel, Workspaces, Pfade und Gerätekennung bleiben außen vor.', copied: 'Kopiert', copyUnavailable: 'Das Kopieren von Bildern ist in dieser Systemansicht nicht verfügbar. Speichern Sie stattdessen die PNG-Datei.',
    myFootprint: 'MEIN AI FOOTPRINT', activeTool: 'AKTIVES TOOL', activeTools: 'AKTIVE TOOLS', localModels: 'LOKALE MODELLE', observedLocally: 'Lokal beobachtet · Forkit AI Footprint', deviceQuestion: 'Wie viel KI arbeitet auf Ihrem Gerät?', shareActive: 'KI-AKTIV',
    clearConfirm: 'Diesen lokalen Monitoring-Verlauf löschen?', scanning: 'Lokale Metadaten werden gescannt…', refreshed: 'Footprint lokal aktualisiert.', scanFailed: 'Der Scan konnte nicht aktualisiert werden.',
    activeShareFallback: 'Unterstützte KI-Tools arbeiteten während {ratio} dieser Beobachtung.', footprintFallback: '{count} unterstützte lokale {records} gefunden.', shareActivity: '{observed} beobachtet; KI aktiv {active} ({ratio}).', shareTool: 'Unterstützte KI-Aktivität: {tools}.', shareModels: '{count} lokale {models}; {storage} erkannte Modelldateien.', captionFirst: 'Meine KI arbeitete während {ratio} dieser Beobachtung aktiv.', captionQuestion: 'Wie viel KI arbeitet tatsächlich auf Ihrem Gerät?',
    appTitle: 'Forkit AI Footprint', menuStopped: '○ Gestoppt', menuMonitoring: '● Monitoring', menuWorking: '● Monitoring · {count} aktiv', openFootprint: 'AI Footprint öffnen', quitForkit: 'Forkit beenden', serviceUnavailable: '○ Dienst nicht verfügbar', serviceStopped: 'Dienst gestoppt',
    closeTitle: 'Forkit überwacht im Hintergrund weiter.', closeBody: 'Über das Forkit-Symbol können Sie die App jederzeit erneut öffnen oder das Monitoring stoppen. Falls die macOS-Menüleiste ausgeblendet ist, bewegen Sie den Zeiger an den oberen Bildschirmrand.', gotIt: 'Verstanden', dontShow: 'Nicht erneut anzeigen', quitTitle: 'Monitoring stoppen und beenden?', keepMonitoring: 'Monitoring fortsetzen', stopQuit: 'Stoppen & beenden', fatalService: 'Der lokale AI-Footprints-Dienst konnte nicht gestartet werden.', fatalStopped: 'Der lokale Dienst wurde unerwartet beendet. Es ist kein Monitoring mehr aktiv.', quit: 'Beenden',
    insightMostlyIdle: 'Diese Beobachtung zeigt ein leichtes KI-Aktivitätsmuster.', insightActivityProduct: '{product} arbeitete während {percent} % Ihrer Beobachtung.', insightActivityGeneric: 'Unterstützte KI-Tools arbeiteten während {percent} % Ihrer Beobachtung.', insightLongest: 'Ihr längster durchgehender KI-aktiver Zeitraum dauerte {duration}.', insightMulti: 'Aktive KI-Arbeit wurde in {count} unterstützten Tools beobachtet.', insightModelsUnused: '{count} lokale Modelle sind für eine zukünftige Sitzung bereit.', insightFocused: 'Die gesamte beobachtete KI-Aktivität stammte von {product}.',
  },
} as const;

export type UiCopyKey = keyof typeof UI_COPY.en;

export function normalizeLocale(value: string | null | undefined): UiLocale { return String(value || '').toLowerCase().startsWith('de') ? 'de' : 'en'; }

export function uiText(locale: UiLocale, key: UiCopyKey, values: Record<string, string | number> = {}): string {
  let text: string = UI_COPY[locale][key];
  for (const [name, value] of Object.entries(values)) text = text.replaceAll(`{${name}}`, String(value));
  return text;
}
